
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("9d021313-4668-49c9-96e4-e8a294b539db")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("Model", "belongTo", "File", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Model.File), "Thumb", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Model.Thumb), True)>
<Assembly: EdmRelationshipAttribute("Model", "fileTo", "File", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Model.File), "TagFile", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Model.TagFile), True)>
<Assembly: EdmRelationshipAttribute("Model", "tagTo", "Tag", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Model.Tag), "TagFile", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Model.TagFile), True)>

#End Region

Namespace Model

    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class Entities
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=Entities", "Entities")
            MyBase.ContextOptions.LazyLoadingEnabled = false
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new Entities object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "Entities")
            MyBase.ContextOptions.LazyLoadingEnabled = false
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new Entities object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "Entities")
            MyBase.ContextOptions.LazyLoadingEnabled = false
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property File() As ObjectSet(Of File)
            Get
                If (_File Is Nothing) Then
                    _File = MyBase.CreateObjectSet(Of File)("File")
                End If
                Return _File
            End Get
        End Property
    
        Private _File As ObjectSet(Of File)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Tag() As ObjectSet(Of Tag)
            Get
                If (_Tag Is Nothing) Then
                    _Tag = MyBase.CreateObjectSet(Of Tag)("Tag")
                End If
                Return _Tag
            End Get
        End Property
    
        Private _Tag As ObjectSet(Of Tag)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property TagFile() As ObjectSet(Of TagFile)
            Get
                If (_TagFile Is Nothing) Then
                    _TagFile = MyBase.CreateObjectSet(Of TagFile)("TagFile")
                End If
                Return _TagFile
            End Get
        End Property
    
        Private _TagFile As ObjectSet(Of TagFile)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Thumb() As ObjectSet(Of Thumb)
            Get
                If (_Thumb Is Nothing) Then
                    _Thumb = MyBase.CreateObjectSet(Of Thumb)("Thumb")
                End If
                Return _Thumb
            End Get
        End Property
    
        Private _Thumb As ObjectSet(Of Thumb)

        #End Region

        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the File EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToFile(ByVal file As File)
            MyBase.AddObject("File", file)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Tag EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToTag(ByVal tag As Tag)
            MyBase.AddObject("Tag", tag)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the TagFile EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToTagFile(ByVal tagFile As TagFile)
            MyBase.AddObject("TagFile", tagFile)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Thumb EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToThumb(ByVal thumb As Thumb)
            MyBase.AddObject("Thumb", thumb)
        End Sub

        #End Region

    End Class

    #End Region

    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="Model", Name:="File")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class File
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new File object.
        ''' </summary>
        ''' <param name="id">Initial value of the id property.</param>
        ''' <param name="name">Initial value of the name property.</param>
        ''' <param name="path">Initial value of the path property.</param>
        ''' <param name="width">Initial value of the width property.</param>
        ''' <param name="height">Initial value of the height property.</param>
        ''' <param name="orientation">Initial value of the orientation property.</param>
        ''' <param name="hash">Initial value of the hash property.</param>
        ''' <param name="create">Initial value of the create property.</param>
        ''' <param name="modify">Initial value of the modify property.</param>
        ''' <param name="active">Initial value of the active property.</param>
        Public Shared Function CreateFile(id As Global.System.Guid, name As Global.System.String, path As Global.System.String, width As Global.System.String, height As Global.System.String, orientation As Global.System.String, hash As Global.System.String, create As Global.System.DateTime, modify As Global.System.DateTime, active As Global.System.Boolean) As File
            Dim file as File = New File
            file.id = id
            file.name = name
            file.path = path
            file.width = width
            file.height = height
            file.orientation = orientation
            file.hash = hash
            file.create = create
            file.modify = modify
            file.active = active
            Return file
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property id() As Global.System.Guid
            Get
                Return _id
            End Get
            Set
                If (_id <> Value) Then
                    OnidChanging(value)
                    ReportPropertyChanging("id")
                    _id = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("id")
                    OnidChanged()
                End If
            End Set
        End Property
    
        Private _id As Global.System.Guid
        Private Partial Sub OnidChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnidChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property name() As Global.System.String
            Get
                Return _name
            End Get
            Set
                OnnameChanging(value)
                ReportPropertyChanging("name")
                _name = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("name")
                OnnameChanged()
            End Set
        End Property
    
        Private _name As Global.System.String
        Private Partial Sub OnnameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property path() As Global.System.String
            Get
                Return _path
            End Get
            Set
                OnpathChanging(value)
                ReportPropertyChanging("path")
                _path = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("path")
                OnpathChanged()
            End Set
        End Property
    
        Private _path As Global.System.String
        Private Partial Sub OnpathChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnpathChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property width() As Global.System.String
            Get
                Return _width
            End Get
            Set
                OnwidthChanging(value)
                ReportPropertyChanging("width")
                _width = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("width")
                OnwidthChanged()
            End Set
        End Property
    
        Private _width As Global.System.String
        Private Partial Sub OnwidthChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnwidthChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property height() As Global.System.String
            Get
                Return _height
            End Get
            Set
                OnheightChanging(value)
                ReportPropertyChanging("height")
                _height = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("height")
                OnheightChanged()
            End Set
        End Property
    
        Private _height As Global.System.String
        Private Partial Sub OnheightChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnheightChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property orientation() As Global.System.String
            Get
                Return _orientation
            End Get
            Set
                OnorientationChanging(value)
                ReportPropertyChanging("orientation")
                _orientation = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("orientation")
                OnorientationChanged()
            End Set
        End Property
    
        Private _orientation As Global.System.String
        Private Partial Sub OnorientationChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnorientationChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property hash() As Global.System.String
            Get
                Return _hash
            End Get
            Set
                OnhashChanging(value)
                ReportPropertyChanging("hash")
                _hash = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("hash")
                OnhashChanged()
            End Set
        End Property
    
        Private _hash As Global.System.String
        Private Partial Sub OnhashChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnhashChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property create() As Global.System.DateTime
            Get
                Return _create
            End Get
            Set
                OncreateChanging(value)
                ReportPropertyChanging("create")
                _create = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("create")
                OncreateChanged()
            End Set
        End Property
    
        Private _create As Global.System.DateTime
        Private Partial Sub OncreateChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OncreateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property modify() As Global.System.DateTime
            Get
                Return _modify
            End Get
            Set
                OnmodifyChanging(value)
                ReportPropertyChanging("modify")
                _modify = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("modify")
                OnmodifyChanged()
            End Set
        End Property
    
        Private _modify As Global.System.DateTime
        Private Partial Sub OnmodifyChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OnmodifyChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property active() As Global.System.Boolean
            Get
                Return _active
            End Get
            Set
                OnactiveChanging(value)
                ReportPropertyChanging("active")
                _active = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("active")
                OnactiveChanged()
            End Set
        End Property
    
        Private _active As Global.System.Boolean
        Private Partial Sub OnactiveChanging(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnactiveChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("Model", "belongTo", "Thumb")>
         Public Property thumbs() As EntityCollection(Of Thumb)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Thumb)("Model.belongTo", "Thumb")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Thumb)("Model.belongTo", "Thumb", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="Model", Name:="Tag")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Tag
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Tag object.
        ''' </summary>
        ''' <param name="id">Initial value of the id property.</param>
        ''' <param name="name">Initial value of the name property.</param>
        ''' <param name="create">Initial value of the create property.</param>
        ''' <param name="modify">Initial value of the modify property.</param>
        ''' <param name="active">Initial value of the active property.</param>
        ''' <param name="count">Initial value of the count property.</param>
        Public Shared Function CreateTag(id As Global.System.Guid, name As Global.System.String, create As Global.System.DateTime, modify As Global.System.DateTime, active As Global.System.Boolean, count As Global.System.Int32) As Tag
            Dim tag as Tag = New Tag
            tag.id = id
            tag.name = name
            tag.create = create
            tag.modify = modify
            tag.active = active
            tag.count = count
            Return tag
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property id() As Global.System.Guid
            Get
                Return _id
            End Get
            Set
                If (_id <> Value) Then
                    OnidChanging(value)
                    ReportPropertyChanging("id")
                    _id = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("id")
                    OnidChanged()
                End If
            End Set
        End Property
    
        Private _id As Global.System.Guid
        Private Partial Sub OnidChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnidChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property name() As Global.System.String
            Get
                Return _name
            End Get
            Set
                OnnameChanging(value)
                ReportPropertyChanging("name")
                _name = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("name")
                OnnameChanged()
            End Set
        End Property
    
        Private _name As Global.System.String
        Private Partial Sub OnnameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnnameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property create() As Global.System.DateTime
            Get
                Return _create
            End Get
            Set
                OncreateChanging(value)
                ReportPropertyChanging("create")
                _create = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("create")
                OncreateChanged()
            End Set
        End Property
    
        Private _create As Global.System.DateTime
        Private Partial Sub OncreateChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OncreateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property modify() As Global.System.DateTime
            Get
                Return _modify
            End Get
            Set
                OnmodifyChanging(value)
                ReportPropertyChanging("modify")
                _modify = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("modify")
                OnmodifyChanged()
            End Set
        End Property
    
        Private _modify As Global.System.DateTime
        Private Partial Sub OnmodifyChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OnmodifyChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property active() As Global.System.Boolean
            Get
                Return _active
            End Get
            Set
                OnactiveChanging(value)
                ReportPropertyChanging("active")
                _active = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("active")
                OnactiveChanged()
            End Set
        End Property
    
        Private _active As Global.System.Boolean
        Private Partial Sub OnactiveChanging(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnactiveChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property count() As Global.System.Int32
            Get
                Return _count
            End Get
            Set
                OncountChanging(value)
                ReportPropertyChanging("count")
                _count = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("count")
                OncountChanged()
            End Set
        End Property
    
        Private _count As Global.System.Int32
        Private Partial Sub OncountChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OncountChanged()
        End Sub

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="Model", Name:="TagFile")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class TagFile
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new TagFile object.
        ''' </summary>
        ''' <param name="id">Initial value of the id property.</param>
        ''' <param name="tagId">Initial value of the tagId property.</param>
        ''' <param name="fileId">Initial value of the fileId property.</param>
        Public Shared Function CreateTagFile(id As Global.System.Guid, tagId As Global.System.Guid, fileId As Global.System.Guid) As TagFile
            Dim tagFile as TagFile = New TagFile
            tagFile.id = id
            tagFile.tagId = tagId
            tagFile.fileId = fileId
            Return tagFile
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property id() As Global.System.Guid
            Get
                Return _id
            End Get
            Set
                If (_id <> Value) Then
                    OnidChanging(value)
                    ReportPropertyChanging("id")
                    _id = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("id")
                    OnidChanged()
                End If
            End Set
        End Property
    
        Private _id As Global.System.Guid
        Private Partial Sub OnidChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnidChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property tagId() As Global.System.Guid
            Get
                Return _tagId
            End Get
            Set
                OntagIdChanging(value)
                ReportPropertyChanging("tagId")
                _tagId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("tagId")
                OntagIdChanged()
            End Set
        End Property
    
        Private _tagId As Global.System.Guid
        Private Partial Sub OntagIdChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OntagIdChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property fileId() As Global.System.Guid
            Get
                Return _fileId
            End Get
            Set
                OnfileIdChanging(value)
                ReportPropertyChanging("fileId")
                _fileId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("fileId")
                OnfileIdChanged()
            End Set
        End Property
    
        Private _fileId As Global.System.Guid
        Private Partial Sub OnfileIdChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnfileIdChanged()
        End Sub

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="Model", Name:="Thumb")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Thumb
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Thumb object.
        ''' </summary>
        ''' <param name="id">Initial value of the id property.</param>
        ''' <param name="fileId">Initial value of the fileId property.</param>
        ''' <param name="image">Initial value of the image property.</param>
        ''' <param name="create">Initial value of the create property.</param>
        ''' <param name="modify">Initial value of the modify property.</param>
        ''' <param name="active">Initial value of the active property.</param>
        Public Shared Function CreateThumb(id As Global.System.Guid, fileId As Global.System.Guid, image As Global.System.Byte(), create As Global.System.DateTime, modify As Global.System.DateTime, active As Global.System.Boolean) As Thumb
            Dim thumb as Thumb = New Thumb
            thumb.id = id
            thumb.fileId = fileId
            thumb.image = image
            thumb.create = create
            thumb.modify = modify
            thumb.active = active
            Return thumb
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property id() As Global.System.Guid
            Get
                Return _id
            End Get
            Set
                If (_id <> Value) Then
                    OnidChanging(value)
                    ReportPropertyChanging("id")
                    _id = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("id")
                    OnidChanged()
                End If
            End Set
        End Property
    
        Private _id As Global.System.Guid
        Private Partial Sub OnidChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnidChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property fileId() As Global.System.Guid
            Get
                Return _fileId
            End Get
            Set
                OnfileIdChanging(value)
                ReportPropertyChanging("fileId")
                _fileId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("fileId")
                OnfileIdChanged()
            End Set
        End Property
    
        Private _fileId As Global.System.Guid
        Private Partial Sub OnfileIdChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnfileIdChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property image() As Global.System.Byte()
            Get
                    Return StructuralObject.GetValidValue(_image)
            End Get
            Set
                OnimageChanging(value)
                ReportPropertyChanging("image")
                _image = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("image")
                OnimageChanged()
            End Set
        End Property
    
        Private _image As Global.System.Byte()
        Private Partial Sub OnimageChanging(value As Global.System.Byte())
        End Sub
    
        Private Partial Sub OnimageChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property create() As Global.System.DateTime
            Get
                Return _create
            End Get
            Set
                OncreateChanging(value)
                ReportPropertyChanging("create")
                _create = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("create")
                OncreateChanged()
            End Set
        End Property
    
        Private _create As Global.System.DateTime
        Private Partial Sub OncreateChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OncreateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property modify() As Global.System.DateTime
            Get
                Return _modify
            End Get
            Set
                OnmodifyChanging(value)
                ReportPropertyChanging("modify")
                _modify = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("modify")
                OnmodifyChanged()
            End Set
        End Property
    
        Private _modify As Global.System.DateTime
        Private Partial Sub OnmodifyChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OnmodifyChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property active() As Global.System.Boolean
            Get
                Return _active
            End Get
            Set
                OnactiveChanging(value)
                ReportPropertyChanging("active")
                _active = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("active")
                OnactiveChanged()
            End Set
        End Property
    
        Private _active As Global.System.Boolean
        Private Partial Sub OnactiveChanging(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnactiveChanged()
        End Sub

        #End Region

    End Class

    #End Region

    
End Namespace
